import { StatCard, ChartData, ManufacturingOrder, InventoryItem, Machine, PurchaseOrder, User, Notification } from './types';

// Dashboard Statistics
export const dashboardStats: StatCard[] = [
  {
    title: 'إجمالي الإنتاج اليومي',
    value: '45,320',
    unit: 'قطعة',
    icon: '📊',
    color: 'from-blue-500 to-blue-600',
    trend: 12,
  },
  {
    title: 'القماش المستهلك',
    value: '2,150',
    unit: 'متر',
    icon: '📦',
    color: 'from-purple-500 to-purple-600',
    trend: -5,
  },
  {
    title: 'الطلبيات النشطة',
    value: '28',
    unit: 'طلب',
    icon: '🚀',
    color: 'from-orange-500 to-orange-600',
    trend: 8,
  },
  {
    title: 'صافي الأرباح اليوم',
    value: '$125,480',
    unit: 'دولار',
    icon: '💰',
    color: 'from-green-500 to-green-600',
    trend: 15,
  },
];

// Weekly Chart Data
export const weeklyChartData: ChartData[] = [
  { name: 'الاثنين', sales: 4200, production: 3800 },
  { name: 'الثلاثاء', sales: 4800, production: 4200 },
  { name: 'الأربعاء', sales: 5200, production: 4800 },
  { name: 'الخميس', sales: 4900, production: 4600 },
  { name: 'الجمعة', sales: 6300, production: 5900 },
  { name: 'السبت', sales: 5800, production: 5400 },
  { name: 'الأحد', sales: 6100, production: 5800 },
];

// Manufacturing Orders
export const manufacturingOrders: ManufacturingOrder[] = [
  {
    id: '1',
    orderNumber: 'PO-2024-001',
    productName: 'قمصان رجالية (أحمر)',
    quantity: 1000,
    unit: 'قطعة',
    currentStage: 'Sewing',
    progress: 65,
    startDate: '2024-07-01',
    expectedDate: '2024-07-08',
    materials: [
      { id: '1', name: 'قماش قطني', quantity: 1500, unit: 'متر' },
      { id: '2', name: 'خيط أحمر', quantity: 50, unit: 'بكرة' },
      { id: '3', name: 'أزرار بلاستيكية', quantity: 6000, unit: 'زر' },
    ],
  },
  {
    id: '2',
    orderNumber: 'PO-2024-002',
    productName: 'بنطلونات جينز (أزرق)',
    quantity: 800,
    unit: 'قطعة',
    currentStage: 'Cutting',
    progress: 30,
    startDate: '2024-07-02',
    expectedDate: '2024-07-10',
    materials: [
      { id: '4', name: 'قماش جينز', quantity: 1600, unit: 'متر' },
      { id: '5', name: 'خيط أزرق', quantity: 40, unit: 'بكرة' },
      { id: '6', name: 'سحاب معدني', quantity: 800, unit: 'سحاب' },
    ],
  },
  {
    id: '3',
    orderNumber: 'PO-2024-003',
    productName: 'فساتين نسائية (وردي)',
    quantity: 500,
    unit: 'قطعة',
    currentStage: 'QA_Inspection',
    progress: 85,
    startDate: '2024-06-28',
    expectedDate: '2024-07-05',
    materials: [
      { id: '7', name: 'قماش شيفون', quantity: 1000, unit: 'متر' },
      { id: '8', name: 'خيط وردي', quantity: 25, unit: 'بكرة' },
      { id: '9', name: 'أربطة ديكور', quantity: 2500, unit: 'قطعة' },
    ],
  },
  {
    id: '4',
    orderNumber: 'PO-2024-004',
    productName: 'جاكيتات رياضية (أسود)',
    quantity: 600,
    unit: 'قطعة',
    currentStage: 'Packaging',
    progress: 95,
    startDate: '2024-06-25',
    expectedDate: '2024-07-03',
    materials: [
      { id: '10', name: 'قماش نايلون', quantity: 1200, unit: 'متر' },
      { id: '11', name: 'سحاب يدوي', quantity: 600, unit: 'سحاب' },
      { id: '12', name: 'شريط عاكس', quantity: 1200, unit: 'متر' },
    ],
  },
  {
    id: '5',
    orderNumber: 'PO-2024-005',
    productName: 'بيجامات أطفال (ملون)',
    quantity: 1200,
    unit: 'قطعة',
    currentStage: 'Pending',
    progress: 5,
    startDate: '2024-07-04',
    expectedDate: '2024-07-12',
    materials: [
      { id: '13', name: 'قماش قطني مطبوع', quantity: 1800, unit: 'متر' },
      { id: '14', name: 'خيط ملون', quantity: 60, unit: 'بكرة' },
      { id: '15', name: 'أزرار بأشكال', quantity: 4800, unit: 'زر' },
    ],
  },
];

// Inventory Items
export const inventoryItems: InventoryItem[] = [
  {
    id: '1',
    name: 'قماش قطني 100%',
    category: 'الأقمشة',
    quantity: 8500,
    unit: 'متر',
    minStock: 2000,
    unitCost: 2.5,
    reorderPoint: 3000,
    status: 'Normal',
  },
  {
    id: '2',
    name: 'قماش جينز دينيم',
    category: 'الأقمشة',
    quantity: 4200,
    unit: 'متر',
    minStock: 1500,
    unitCost: 3.8,
    reorderPoint: 2500,
    status: 'Normal',
  },
  {
    id: '3',
    name: 'قماش شيفون',
    category: 'الأقمشة',
    quantity: 1200,
    unit: 'متر',
    minStock: 800,
    unitCost: 4.2,
    reorderPoint: 1200,
    status: 'Low',
  },
  {
    id: '4',
    name: 'قماش نايلون',
    category: 'الأقمشة',
    quantity: 450,
    unit: 'متر',
    minStock: 1000,
    unitCost: 5.0,
    reorderPoint: 1500,
    status: 'Critical',
  },
  {
    id: '5',
    name: 'خيط أحمر',
    category: 'الخيوط والإضافات',
    quantity: 125,
    unit: 'بكرة',
    minStock: 50,
    unitCost: 0.75,
    reorderPoint: 80,
    status: 'Normal',
  },
  {
    id: '6',
    name: 'خيط أسود',
    category: 'الخيوط والإضافات',
    quantity: 30,
    unit: 'بكرة',
    minStock: 50,
    unitCost: 0.75,
    reorderPoint: 80,
    status: 'Critical',
  },
  {
    id: '7',
    name: 'أزرار بلاستيكية',
    category: 'الخيوط والإضافات',
    quantity: 15000,
    unit: 'زر',
    minStock: 5000,
    unitCost: 0.02,
    reorderPoint: 8000,
    status: 'Normal',
  },
  {
    id: '8',
    name: 'سحاب معدني',
    category: 'الأجزاء المعدنية',
    quantity: 3200,
    unit: 'سحاب',
    minStock: 1000,
    unitCost: 0.5,
    reorderPoint: 1500,
    status: 'Normal',
  },
  {
    id: '9',
    name: 'سحاب يدوي',
    category: 'الأجزاء المعدنية',
    quantity: 800,
    unit: 'سحاب',
    minStock: 500,
    unitCost: 0.3,
    reorderPoint: 800,
    status: 'Low',
  },
  {
    id: '10',
    name: 'شريط عاكس',
    category: 'الأجزاء والديكورات',
    quantity: 5500,
    unit: 'متر',
    minStock: 2000,
    unitCost: 0.8,
    reorderPoint: 3000,
    status: 'Normal',
  },
];

// Machines
export const machines: Machine[] = [
  {
    id: '1',
    name: 'ماكينة القص الأوتوماتيكية - 1',
    status: 'Running',
    efficiency: 92,
    availability: 98,
    quality: 96,
    oee: 87,
    productionRate: 150,
    downtimeMinutes: 12,
  },
  {
    id: '2',
    name: 'ماكينة الخياطة - 1',
    status: 'Running',
    efficiency: 88,
    availability: 95,
    quality: 94,
    oee: 79,
    productionRate: 120,
    downtimeMinutes: 30,
  },
  {
    id: '3',
    name: 'ماكينة الخياطة - 2',
    status: 'Running',
    efficiency: 85,
    availability: 92,
    quality: 90,
    oee: 70,
    productionRate: 110,
    downtimeMinutes: 48,
  },
  {
    id: '4',
    name: 'ماكينة فحص الجودة',
    status: 'Idle',
    efficiency: 0,
    availability: 100,
    quality: 0,
    oee: 0,
    productionRate: 0,
    downtimeMinutes: 0,
  },
  {
    id: '5',
    name: 'ماكينة التعبئة والتغليف',
    status: 'Running',
    efficiency: 90,
    availability: 96,
    quality: 98,
    oee: 85,
    productionRate: 200,
    downtimeMinutes: 15,
  },
];

// Purchase Orders
export const purchaseOrders: PurchaseOrder[] = [
  {
    id: 'PO-2024-INV-001',
    itemId: '4',
    itemName: 'قماش نايلون',
    quantity: 2000,
    unit: 'متر',
    supplier: 'شركة النيل للأقمشة',
    estimatedCost: 10000,
    status: 'Draft',
    createdDate: '2024-07-05',
  },
];

// Users Database - مشغل الأحلام للخياطة
export const users: User[] = [
  {
    id: '1',
    name: 'مدير الأحلام',
    email: 'admin',
    password: '0000',
    role: 'admin',
    department: 'الإدارة العليا',
    createdAt: '2024-01-01',
  },
  {
    id: '2',
    name: 'مشرف الإنتاج',
    email: 'manager',
    password: '0000',
    role: 'manager',
    department: 'الإنتاج',
    createdAt: '2024-02-01',
  },
  {
    id: '3',
    name: 'موظف العمليات',
    email: 'staff',
    password: '0000',
    role: 'staff',
    department: 'العمليات',
    createdAt: '2024-03-01',
  },
];

// Alerts & Notifications
export const initialAlerts: Notification[] = [
  {
    id: '1',
    type: 'error',
    category: 'inventory',
    title: 'مخزون حرج!',
    message: 'قماش نايلون انتهى - الكمية: 450 متر فقط (الحد الأدنى: 1000)',
    timestamp: new Date(Date.now() - 5 * 60000).toISOString(),
    read: false,
    actionUrl: '/inventory',
  },
  {
    id: '2',
    type: 'warning',
    category: 'inventory',
    title: 'كمية منخفضة',
    message: 'خيط أسود بحاجة إعادة طلب - الكمية: 30 بكرة',
    timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
    read: false,
    actionUrl: '/inventory',
  },
  {
    id: '3',
    type: 'warning',
    category: 'machine',
    title: 'ماكينة بحاجة صيانة',
    message: 'ماكينة الخياطة - 2 تحتاج صيانة دورية (آخر صيانة: 45 يوم)',
    timestamp: new Date(Date.now() - 30 * 60000).toISOString(),
    read: true,
    actionUrl: '/oee',
  },
  {
    id: '4',
    type: 'success',
    category: 'order',
    title: 'طلبية مكتملة',
    message: 'الطلبية PO-2024-001 اكتملت بنجاح',
    timestamp: new Date(Date.now() - 2 * 3600000).toISOString(),
    read: true,
    actionUrl: '/manufacturing',
  },
  {
    id: '5',
    type: 'info',
    category: 'system',
    title: 'تحديث النظام',
    message: 'تم تحديث نظام الإدارة إلى الإصدار 2.1',
    timestamp: new Date(Date.now() - 24 * 3600000).toISOString(),
    read: true,
  },
];
